# Ultra-Simple iOS Workflow - Uses Available Device Names
name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Show Available Devices
      run: |
        echo "=== Available iOS Simulators ==="
        xcrun simctl list devices available | grep iPhone
      
    - name: Build Project
      working-directory: ./WishDirectory
      run: |
        xcodebuild build \
          -project WishDirectory.xcodeproj \
          -scheme WishDirectory \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Test Project  
      working-directory: ./WishDirectory
      run: |
        xcodebuild test \
          -project WishDirectory.xcodeproj \
          -scheme WishDirectory \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO