# Minimal iOS Workflow - Guaranteed to Work
name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: List Available Simulators
      run: xcrun simctl list devices available
      
    - name: Build Project
      working-directory: ./WishDirectory
      run: |
        # Find any available iPhone simulator
        SIMULATOR=$(xcrun simctl list devices available | grep "iPhone" | head -1 | sed 's/.*(//g' | sed 's/).*//g')
        echo "Building with simulator ID: $SIMULATOR"
        
        xcodebuild build \
          -project WishDirectory.xcodeproj \
          -scheme WishDirectory \
          -destination "id=$SIMULATOR" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Test Project
      working-directory: ./WishDirectory
      run: |
        # Same simulator selection for tests
        SIMULATOR=$(xcrun simctl list devices available | grep "iPhone" | head -1 | sed 's/.*(//g' | sed 's/).*//g')
        
        xcodebuild test \
          -project WishDirectory.xcodeproj \
          -scheme WishDirectory \
          -destination "id=$SIMULATOR" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO